### ISSUE TITLE
display base offset above helix major ticks, and distance between major ticks

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#14]
Display the integer base offset of each major tick drawn in a `Helix` above the topmost helix.

Perhaps have some way to show the offset lightly over *every* `Helix` (careful not to obscure parts of the design in doing this).

**Comment by dave-doty** [comment]
Also display the distance between two major tick marks.

Each of these should be boolean options under the View menu that can disabled.

**Comment by UnHumbleBen** [comment]
Where should the distance between two major tick marks be displayed? 

Also, to clarify, I imagine I would display the base offset of the offset to the *right* of the major tick? For instance, the first major tick should have a "0" on top of it, the second major tick should have an "8" on top of it for a default major tick distance of 8.

**Comment by dave-doty** [comment]
Yes, that sounds reasonable. 

I'm not sure exactly where is optimal for either. I was thinking the offsets of the major ticks would be somewhere near the major ticks, and the distances between major ticks would be about halfway in between them.

But as long as any constants used are declared at the top of the file with the React component, then it should be straightforward to fiddle with it until it looks good.
