### ISSUE TITLE
Making a strand that has either the same start or end offset as another strand, but different helix and direction crashes

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#174]
Reproduce the bug by:

1. Loading empty design
2. Adding 2 helices
3. On helix 0, make a strand (doesn't matter what offsets or direction is)
4. On helix 1, make a strand in the reverse direction of the earlier strand such that it either shares the same start offset or end offset with the earlier strand

**Comment by dave-doty** [comment]
What is the precise error you get? Can you paste the stack trace?

I can't reproduce this on either Chrome

![image](https://user-images.githubusercontent.com/19274365/73678456-46b70300-466d-11ea-9020-95c4727ac0d8.png)

or Firefox

![image](https://user-images.githubusercontent.com/19274365/73678526-66e6c200-466d-11ea-8e45-39b30f4c6063.png)

**Comment by UnHumbleBen** [comment]
The bug is fixed now. This bug first appears on this commit commit: 1a09740bf54b5ec47275bf7f8557c3caa63acd1f
