### ISSUE TITLE
text along paths in exported SVG is not displayed properly in Inkscape

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#177]
The export SVG feature seems to work to create SVG files readable by browsers and many viewers. 

However, the widely-used Inkscape program does not properly display [textPaths](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath), which render text along a path. The three things displayed as textPaths are the length of an insertion, the DNA bases in an insertion, and the DNA bases along a loopout.

In Inkscape, they bunch up near the origin instead of being drawn along the length of the insertion path.

**Comment by drhaley** [comment]
With the default Linux viewer they also appear bunched: 
![image](https://user-images.githubusercontent.com/14882746/73990198-4c2a7c80-48fd-11ea-91ad-fe94d1df2b77.png)
