### ISSUE TITLE
Example button and context menus are not responsive if page loads with no dna design

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#186]
Clicking the example button should show a dialog box prompting the user to select an example, but this dialog box is not showing up. The Redux action `DialogShow` is firing but the view is not updated

**Comment by dave-doty** [comment]
I noticed this myself on http://scadnano.org/, but couldn't reproduce it in the sense that I went back and the example button worked (and does for me now).

It never happens on https://web.cs.ucdavis.edu/~doty/scadnano/ or on the local dev server. Can you get it to happen in either of those places?

**Comment by UnHumbleBen** [comment]
The bug appears in both places, and even in the Github hosted site
scadnano.org

**Comment by dave-doty** [comment]
By "both places", you mean both https://web.cs.ucdavis.edu/~doty/scadnano/ and the local dev server you run?

**Comment by UnHumbleBen** [comment]
Yes

**Comment by UnHumbleBen** [comment]
It seems that this bug only occurs when the application begins to load with no initial dna design. If you clear local storage and refresh the page, the example button will not be responsive. Interestingly, if you load a dna example, the example button is still not responsive (the div containers are missing from the DOM). It's is not until the page is refreshed that these contains are added to the DOM, and the example button and other context menu button work

**Comment by dave-doty** [comment]
We've been hit by something like this before.

Can you add some unit/component tests to reproduce this? Specifically unit tests that test the condition that no design is loaded in localStorage already, because such bugs will be likely to go unnoticed by us (since we have designs in localStorage) but will hit every new user.

**Comment by UnHumbleBen** [comment]
@dave-doty Any ideas why the Export DNA dialog box still works even if the example and context menus are not responsive?

**Comment by dave-doty** [comment]
Nope.

**Comment by dave-doty** [comment]
Oh, sorry, yes, I know why that is. It still uses an older package for making the dialog. I didn't replace it with my custom dialog stuff yet (which is what is making the error happen).

BTW I think I fixed the error. I'll commit it now.
