### ISSUE TITLE
Compile README.md into README.html for main site

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#189]
One of the things my compile.sh script does is compile README.md into README.html, which is why README.html is available on the server:

https://web.cs.ucdavis.edu/~doty/scadnano/README.html 

But it's not available on the main site: 

http://scadnano.org/README.html

**Comment by UnHumbleBen** [comment]
The only way I can come up with so far is to manually run pandoc locally before running `peanut`. There are a few issues with this approach though:
1. Requires removing README.html from .gitignore, which is ugly
2. For some reason, the README file is hosted on http://scadnano.org/README instead of http://scadnano.org/README.html, which is inconsistent with the behavior in https://web.cs.ucdavis.edu/~doty/scadnano/
3. A bit annoying to have to have to remember to run `pandoc` before running `peanut`

**Comment by dave-doty** [comment]
I suppose it's okay if this isn't automated. I'll just add README.html to the repo and manually run pandoc when I want it updated.

Not sure what you mean by this: *"For some reason, the README file is hosted on http://scadnano.org/README instead of http://scadnano.org/README.html"*

**Comment by UnHumbleBen** [comment]
Hm, Github had a habit of fixing issues immediately right after I post
them. Both links work now, not sure why. The second link (
http://scadnano.org/README.html) used to load a 404 page, but now it’s fine

**Comment by dave-doty** [comment]
I got rid of READMG.html and just rely on README.md on the GitHub website, so this is moot.
