### ISSUE TITLE
elements far from origin disappear on mouseover when selectable

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#20]
This appears to be related to the SVG filter used to create a shadow around the element.

This only appears on large designs, for instance examples/output-designs/6_helix_bundle_honeycomb.dna when putting the cursor over strands on the far right side.

**Comment by dave-doty** [comment]
This was caused by using the focus SVG filter.

https://github.com/UC-Davis-molecular-computing/scadnano/blob/41abc916d93b932ae075bc9bead25ddec12edfc8/lib/src/view/svg_filters.dart

It's been disabled for now:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/3678633189a21726e4f9803d91144dc23383428a/web/scadnano-styles.css#L430-L432

https://github.com/UC-Davis-molecular-computing/scadnano/blob/3678633189a21726e4f9803d91144dc23383428a/web/scadnano-styles.css#L487-L489

but I like how it emphasizes what is selectable, and what is selected, and want to figure out how to get it back working again.

The problem can be mitigated by setting these values even larger:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/41abc916d93b932ae075bc9bead25ddec12edfc8/lib/src/view/svg_filters.dart#L25-L28

but no matter how large they are, in a sufficiently large design, the effect still happens.

**Comment by dave-doty** [comment]
This still happens with crossovers between adjacent ends on the same helix.

We use this in some designs to break up parts of a strand into multiple domains on the same helix, e.g.,:

![image](https://user-images.githubusercontent.com/19274365/86987310-9b920480-c14a-11ea-89d9-ab7c4b1d2437.png)

Here's what it looks like when those crossovers are selected:

![image](https://user-images.githubusercontent.com/19274365/86987331-a8165d00-c14a-11ea-9f28-073d6238dd60.png)

The vertical crossovers appear with the shadow, but the horizontal crossovers simply disappear.

**Comment by dave-doty** [comment]
I made domains selectable (#416), and this issue appears when using the shadow filter to highlight the lines. They disappear (not just when hovering, but they STAY disappeared).

For now, the fix is that domains do not get the shadow filter on hover or being selected. Instead, they turn pink and slightly thicker. But I do like the shadow filter, so if we can figure out a way to make it work with lines, that would be great.

These links claim to solve the problem, but they doesn't fix it for me: 

https://stackoverflow.com/questions/36284828/svg-adding-shadow-filter-makes-straight-line-invisible
https://stackoverflow.com/questions/47758565/adding-fedropshadow-to-a-vertical-line-in-svg-makes-it-disappear

**Comment by UnHumbleBen** [comment]
Adding `filterUnits="userSpaceOnUse"` seems to work for me:

![scadnano-domain-shadow-filter](https://user-images.githubusercontent.com/31255679/93926589-8ef26680-fccc-11ea-852d-65435faf68d6.gif)

**Comment by UnHumbleBen** [comment]
I am confused on why the strand selection works then. If an individual line can't be shadowed, why can strands (group of lines) be shadowed?

**Comment by UnHumbleBen** [comment]
The initial issue has been resolved. Moving issue to #534
