### ISSUE TITLE
Hanging loopout at end of strand generates awkard error

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano#200]
If the last substrand of a strand is a Loopout (that should not happen in principle but nothing prevents you from doing it, as of right now, in the python library), the interface crashes with an awkward message, cf screenshot and .dna file on pastebin:

https://pastebin.com/kCqasjqM

![Screenshot from 2020-02-20 15-04-09](https://user-images.githubusercontent.com/7616128/74965927-fdf19f00-540d-11ea-987c-af70e8caf801.png)

**Comment by dave-doty** [comment]
Would you mind also attaching the `.dna` file? If you rename the extension to `.txt` GitHub allows it to be attached. (Or just paste its contents in a comment.)

**Comment by dave-doty** [comment]
@UnHumbleBen, this is a special case of issue #9.
