### ISSUE TITLE
support adding/editing/removing DNA modifications in web interface

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#208]
Current DNA modifications can only be created and editing in the Python scripting library. Support adding, editing, and removing them in the web interface.

This should be done via the right-click context menu on strands.

It should be implemented like this. There is a single option on the context menu, "add modification". The dialog that is brought up will allow them to specify 5', 3', or internal modification via radio button (as well as the associated data)

But it should be auto-populated based on how they clicked. If they clicked on the 5' end or 3' end of the strand, then that will be the default (this may require the click handler to be placed in multiple components, i.e., on domain lines and also no 5'/3' ends).

If they clicked on a domain line, then the offset should be calculated where they clicked and translated into an index into the DNA sequence. (This logic is tricky; see the code that draws DNA sequences, and also that assigns complementary DNA to a strand that is bound to one being assigned DNA, to see some of the helper functions available.)

There should also be an option to right click on a modification to edit or remove it.

**Comment by rishabhmudradi** [comment]
I was a little confused on what exactly 'if they clicked on the 5' end or 3' end of the strand, then that will be the default' meant. Does this mean that a user is not required to specify a modification?

**Comment by dave-doty** [comment]
If they right-click on the 5' end, then the default choice when the dialog comes up is a 5' modification (but they can still change it in the dialog).

If they instead right-click on a domain line, then the default is an internal modification (again, which can be changed in the dialog).

I want to balance keeping the right-click context menu small (only having 1 more option to click) but still using where they clicked to initially populate the choice with something reasonable (i.e., if they right click on the 5' end of a strand, they likely wanted to add a modification to the 5' end; if they right click on a particular offset of a domain, they likely want to add an internal modification at that offset).

**Comment by dave-doty** [comment]
BTW, look at examples of other dialogs (e..g, assign DNA sequence for strand or change min offset for Helix) to see examples of how to pop up a dialog to get information from the user. In particular check out the file state/dialog.dart. (unfortunately not documented super carefully; perhaps we should add some comments to explain how they work, but hopefully looking at examples of how they are used is helpful)

**Comment by rishabhmudradi** [comment]
Got it, that makes sense. And to clarify, in order to remove or edit a modification we would just right click on that specific modification?

**Comment by dave-doty** [comment]
> 
> 
> Got it, that makes sense. And to clarify, in order to remove or edit a modification we would just right click on that specific modification?


Yes, if you right-click the modification, it should give two options in the context menu:

- edit modification
- remove modification

**Comment by rishabhmudradi** [comment]
Currently, I have it so if a user clicks on a specific domain they can add a modification int at that offset; similarly, if a user clicks on a dna_end they can also add the modification there. But if a user clicks on a whole strand should they still be able to add modifications? I read this: 'This should be done via the right-click context menu on strands.' But was confused if all 3 modifications should be allowed to be added if you right click on a strand.

**Comment by dave-doty** [comment]
Sorry, I said "Strand", but I really meant "right click on domain line or 5' end or 3' end".

If you check the View component design_main_strand.dart, you'll see there's no right-click context menu handling code. The context menu for the strand is *defined* there:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/67d59d8703067d5add104f1d1f1547abc256c0d4/lib/src/view/design_main_strand.dart#L246-L325

but it only shows up if you right-click on a domain line:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/67d59d8703067d5add104f1d1f1547abc256c0d4/lib/src/view/design_main_strand_domain.dart#L149-L159

A different context menu is shown if you right-click on a crossover, for instance:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/0165e552eb4589fd8f52c7f9a37c1c5860c81327/lib/src/view/design_main_strand_crossover.dart#L150-L169

If you right-click on a 5' or 3' end, it brings up the strand context menu, but right now I'm not sure why. I'll look into it later.

So the way to add these options is to add new lines of code to some of these context menu definitions. We can chat about this in person later today if that would help.

**Comment by rishabhmudradi** [comment]
I think that would be helpful, I can call anytime after 4:30 today.

**Comment by rishabhmudradi** [comment]
It doesn't look like modifications have an id() method I can access for the query selector, so I was planning on adding it to modification. If I was to add this to the Modification state, should I simply set the id to be:
`String mod_id() => 'modification-${display_text}';`
