### ISSUE TITLE
exception thrown in caching image code

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#212]
Open scadnano-python-package/examples/output-designs/16_helix_origami_rectangle.dna. You will see this:

![image](https://user-images.githubusercontent.com/19274365/77093545-59408e00-69c8-11ea-92fb-25ad8aefcb15.png)

**Comment by UnHumbleBen** [comment]
@dave-doty I'm having difficulty reproducing the bug. I did sometimes see that message, but now I am unable to even after loading 16_helix_origami_rectangle.dna. Do you have an idea for what are the specific conditions where this bug occurs?

**Comment by dave-doty** [comment]
Nope, I didn't look into it carefully.

Sometimes difficult to reproduce bugs involve localStorage. Try clearing it out to see if that helps reproduce.

**Comment by UnHumbleBen** [comment]
@dave-doty did the error message pop up while the DNA checkbox was turned off? Then it would be the bug noted here #213

**Comment by dave-doty** [comment]
Yes, "show DNA" was turned off.

**Comment by dave-doty** [comment]
The same bug (at the same line of code) can be triggered by trying to zoom in or out.

**Comment by UnHumbleBen** [comment]
Closed by this [commit](https://github.com/UC-Davis-molecular-computing/scadnano/commit/b8da175cc602e40ce8e0c54c2b138bc02b0de251)
