### ISSUE TITLE
add copy/cut/paste to Edit menu dropdown

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#225]
Currently copy/cut/paste is only available via Ctrl+C/Ctrl+X/Ctrl+V keyboard shortcuts. Add it to the Edit menu.

**Comment by UnHumbleBen** [comment]
@dave-doty I don't believe Ctrl+X is an available option yet.

**Comment by dave-doty** [comment]
Oh, right, that's not implemented. Actually I forgot that it's not really needed, because move is implemented via select, then click and drag.
