### ISSUE TITLE
Copy and paste does not work on built version

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#229]
After user selects a strand, and tries to paste, the usual faded strand is no where to be seen. The strand seems to be pasted in place, so nothing happens. This only seems to be an issue in the built version (created from running `webdev build` or `webdev serve --release`), but `webdev serve` works just fine.

**Comment by UnHumbleBen** [comment]
Mistake on my end, my strand was just so long that I didn't have room for the new strand to paste.

**Comment by dave-doty** [comment]
Maybe we should render the strand even if it can't be pasted, in a different color or faded. I've had this happen to me a few times as well, where I just didn't realize the set of strands I had copied was going off the end of the helices.
