### ISSUE TITLE
use hashCode caching in built_value

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#231]
built_value version 7.1.0 supports caching of the `hashCode` value for built objects. This has the potential to speed up rendering by reducing the cost to do Map/Set lookups:

https://pub.dev/packages/built_value#-changelog-tab-

But it requires doing this for each built_value class we have:

Write an abstract getter `int get hashCode;` then annotate it with `@memoized` to turn this on for a built_value class.

**Comment by UnHumbleBen** [comment]
Running into an issue with the memozied hashcode: https://github.com/google/built_value.dart/issues/870

**Comment by UnHumbleBen** [comment]
@dave-doty , I don't see much of a speedup after adding the memoized hashcode for a few of the classes (`Strand`, `Helix`, etc.) so I suspect the performance issue lie somewhere else.
