### ISSUE TITLE
organize all localStorage-persisted UI settings into one subtree of AppUIState 

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#236]
Currently, when a new setting is added to the UI, e.g., autofit, then one must remember to add the boilerplate code that saves/retrieves it from localStorage. It is easy to forget, e.g. #230, and worse yet, not fast to implement. This issue proposed making it as simple as adding an extra `implements` line to appropriate actions.

Since settings like this are not much data, it is not expensive to write them all at once each time any of them changes.

So, this would be simpler to organize as follows: put all such settings under a single subtree of `AppUIState`, called `AppUIStateStorable`. Not all of `AppUIState` would go there, e.g., `strands_move`, `mouseover_datas`, `dialog`, `strand_creation`, `side_view_grid_position_mouse_cursor`, and others are ephemeral and don't need to be persisted. 

But many do need to be persisted, e.g., `show_dna`, `show_modifications`, `loaded_filename`, etc. The `SelectMode` and `EditMode` are also under here.

Then, the only boilerplate needed is to introduce a new `Action` interface called `AppUIStateStorableAction`.

Any `Action` changing one of these settings should implement `AppUIStateStorableAction`. Unlike `StorableAction`, there's no need to have a method `storables()` indicating which data to store. An `AppUIStateStorableAction` triggers *all* of `AppUIStateStorable` to be written into localStorage.

**Comment by UnHumbleBen** [comment]
To clarify, you want one of the fields of `ui_state` to be something like
```
AppUIStateStorable get storable;
```
And `storable` would have as it's fields `show_dna`, `show_modifications`, and other actions that should be stored in local storage. So whenever we want to access `show_dna`, we would access it by `app.state.ui_state.storable.show_dna` (or maybe we can make a getter in for `AppUIState`, that directly accesses the storable fields.

**Comment by dave-doty** [comment]
Yes. Maybe call it `storables` instead.

I'm happy also to have getters in `ui_state` for all of them to make it easier to reuse the existing code.

The main thing is to have middleware/local_storage.dart rewritten so that it no longer needs to be updated when we add a new storable field. The only thing to remember should be to ensure actions modifying any of those variables implement `AppUIStateStorableAction`.

**Comment by UnHumbleBen** [comment]
Should `loaded_filename` be included in `AppUIStateStorableAction`? It seems to have some special treatment in the `local_storage.dart` middleware as it is not an enum of `Storage` and seems to be tied in with `dna_design`. Can you explain why `loaded_filename` is not an enum of `Storage`?

**Comment by dave-doty** [comment]
I'm not sure why it's different. I think it should be treated the same as the others. It's probably just older.

I think when it's done, there will be only two things that localStorage stores: `state.dna_design`, and `state.ui_state.storables`.
