### ISSUE TITLE
Update modifications in the view when helices change

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#237]
Currently, modifications are not redrawn when the helix it is on changes position (from selecting a certain helix) or when a helix is removed.

**Comment by dave-doty** [comment]
Also, when one domain on a strand is deleted, modifications on the remaining domains are removed.

**Comment by dave-doty** [comment]
I fixed #260, which also fixed the issues mentioned in Ben's original post. But the issue I mentioned in the comment (one domain on a strand is deleted, modifications on the remaining domains are removed) remains.
