### ISSUE TITLE
drag and drop to load file

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#243]
Implement drag-and-drop to load .dna files.

If a non-empty design is loaded, (i.e., if there is a design, and it has any helices), then a confirm dialog should be displayed before replacing the loaded design.

**Comment by dave-doty** [comment]
From Matt Patitz:

Here's a possible beginning (taken from here: https://stackoverflow.com/questions/10261989/html5-javascript-drag-and-drop-file-from-external-window-windows-explorer)

```javacript
var dropZone = document.getElementById('dropZone');

// Optional.   Show the copy icon when dragging over.  Seems to only work for chrome.
dropZone.addEventListener('dragover', function(e) {
    e.stopPropagation();
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
});

// Get file data on drop
dropZone.addEventListener('drop', function(e) {
    e.stopPropagation();
    e.preventDefault();
    var files = e.dataTransfer.files; // Array of all files

    for (var i=0, file; file=files[i]; i++) {
        if (file.type.match(/image.*/)) {
            var reader = new FileReader();

            reader.onload = function(e2) {
                // finished reading file data.
                var img = document.createElement('img');
                img.src= e2.target.result;
                document.body.appendChild(img);
            }

            reader.readAsDataURL(file); // start reading the file data.
        }
    }
});
```

**Comment by dave-doty** [comment]
This should response to the user dragging the file anywhere onto the window. Before doing anything, it should pop up a confirmation dialog (window.confirm) asking the user if they really want to replace the current design. See middleware/helix_remove.dart for an example.

If the user clicks Yes, then fire a `LoadDNAFile` action with the file's contents and name.

**Comment by UnHumbleBen** [comment]
@dave-doty I wasn't sure how to check if DNADesign is empty, so confirmation dialog is made whenever the user drops a file, even if there is no loaded dna design.

**Comment by dave-doty** [comment]
Sorry, I should have been more specific. It's related to this line:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/lib/src/view/design.dart#L431

If `state.has_error()` is `true`, then there's no design to display, which is what I meant by "empty". For instance, if you clear your browser's local storage of the key `scadnano:dna_design` and reload the page, then the "error" will be that there is no design loaded, and it gives a message indicating how to load one:

![image](https://user-images.githubusercontent.com/19274365/82066876-d6b11380-9684-11ea-9b41-574ca55ab382.png)
