### ISSUE TITLE
remove rotation and rotation anchor from JSON and model; use roll instead

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#263]

**Comment by UnHumbleBen** [comment]
Supposed a helix has a nonzero `min_offset` of 0. Should a `roll` angle of `0` imply that the backbone angle is 0 at offset 0 (this offset isn't actually allowed for this helix), or at wherever the `min_offset` is? For instance, if a helix has a min_offset of 2 and a roll of 0, should the backbone angle at offset 2 be around 69 degrees (meaning we treat the imaginary offset 0 as having the backbone angle of 0), or should the backbone angle at offset 2 be 0 degrees?

Essentially, `roll` would replace `rotation`, and I'm deciding whether `rotation_anchor` should be replaced with `0` or `min_offset`. I tried looking at `codenano`'s documentation but I couldn't find what offset `roll` refers to.

**Comment by dave-doty** [comment]
I'm not sure yet. I think probably the easiest is it roll of 0 means backbone is pointing up at offset 0, even if min_offset is not 0.

But there's a bigger issue I don't know how to solve yet. Right now, either position or grid_position can be specified, but not both. So how can we handle roll when grid_position is set (and not position)? It might actually make sense to allow both grid_position and position to be defined, but I'm not sure yet.

This might be something we should hash out with the codenano people first.
