### ISSUE TITLE
menu should disappear when certain items are clicked

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#265]
For instance, when clicking File-->Open or File-->Save, the menu should disappear after clicking the option.

It should stay visible for others, such as anything under View, since a user might want to check many of those at once.

**Comment by UnHumbleBen** [comment]
Save already disappears after clicking. So the only buttons I identified that do not close the menu is File --> Open
File --> Import cadnano v2
View --> anything

So, I can make it so that the two File buttons will make menu disappear, but leave view alone.
