### ISSUE TITLE
add unit tests for strand editing with modifications

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#266]
Currently, the unit tests don't check whether modifications are properly moved from previous strands to new strands when strands are merged or split through the following editing operations:

- split
  - delete crossover
  - delete loopout
  - delete domain
  - nick
- merge
  - new crossover
  - ligate
- other edits
  - move 5'/3' ends
  - move strands
  - copy/paste strands

Check that modifications are preserved as appropriate in each case.

For splitting and merging, include at least one strand with many domains and check complex examples, e.g., domains 1-7, and crossovers between 2-3 and between 5-6 are removed.

**Comment by UnHumbleBen** [comment]
Just want to verify that this is the expected behavior of making crossovers when there are modifications on the end that is about to cross:

Before:
![scadnano_mod_crossover_before](https://user-images.githubusercontent.com/31255679/83112224-b452c900-a07a-11ea-9f3f-bb5cf4e0d3f1.png)

After crossing, the modification disappears:
![scadnano_crossover_mod_after](https://user-images.githubusercontent.com/31255679/83112238-b87ee680-a07a-11ea-8076-160ece64bf1a.png)

Is this the intended behavior?

**Comment by dave-doty** [comment]
Yes, that's expected behavior. The alternative would be to convert it to an internal modification, or move it to the end of the newly formed strand, but I don't picture a scenario where that would actually be what a user would want.

Oddly, internal modifications are much rarer to use in practice, since they are more expensive and less reliable to attach. So it's odd that a huge amount of the complexity of our code is handling them.

**Comment by UnHumbleBen** [comment]
I notice you specified that you want unit tests for removing loopouts but what about adding loopouts? I notice that the app crashes if adjusting the length of a loopout causes the modification to end up on the loopout.

For instance load, [many_helices_modifications.dna](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/blob/master/examples/output_designs/many_helices_modifications.dna) and set loopout length from 1 to 8 on the crossover connecting helix 2 to 3. This attempts to move the Cy3 modification on helix 3, offset 8 into the loopout, causing a crash

**Comment by UnHumbleBen** [comment]
In regard to nicks. Suppose a user nicks at an internal modification. The modification is now on a 5 prime end or three prime end, but currently, it is still considered an internal modification. Should the modification type be converted to 5 prime or 3 prime?

**Comment by dave-doty** [comment]
I don't think we should convert. Just leave the modification as it is.

Not all internal modifications are the same, but the most common thing is that it is attached to the base itself, whereas 5' or 3' modifications are attached to the phosphate backbone, which is a different region of the chemical structure:

![image](https://user-images.githubusercontent.com/19274365/83279440-f4ed3800-a189-11ea-9cf8-33faa6b8a1d3.png)

So for example, one could have an internal biotin on a base that happens to be at the 5' end of the strand, which would look like this (here it shows the biotin attached by a linker to a T base), except that the squiggly line on the left would not connect to any more DNA:

![image](https://user-images.githubusercontent.com/19274365/83279680-50b7c100-a18a-11ea-8622-1732f4e5787f.png)

But a 5' biotin modification instead means that the squiggly line on the right has this connected to it:

![image](https://user-images.githubusercontent.com/19274365/83279790-8066c900-a18a-11ea-9477-a748e7935ebd.png)

Now, there's probably no reason to use an internal modification on a base that happens to be at the 5' or 3' end. Internal modifications are less reliable and more expensive to attach, so if you actually want it at the 5' or 3' end, you would probably want the 5'/3' version. But there's no reason for the software to enforce that.
