### ISSUE TITLE
Clear helix selections when loading new design

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#280]
Currently, when a design has selected helices and a new design is loaded, the same selected helices are selected in the new design after loading. This seems unnatural because the old design's selected helices might have nothing to do with the new design's helices.

**Comment by dave-doty** [comment]
Instead, let's make clearly the selected helices an option.

Sometimes you are writing a local script and repeatedly loading it into the web interface. If it is a big 3D design, you might like to keep the same helices selected.
