### ISSUE TITLE
cache DNA image for speed

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#30]
When showing DNA for a full origami (~14,000 bases), rendering while panning and zooming is quite slow when most of the DNA is visible. The SVG rendering engine is smart enough not to render objects that are not in the viewport, however, so it is fast when zoomed in. Since the detail of SVG (compared to a pixelated PNG) is only needed on zoom in, cache a low-resolution PNG image to display instead when the zoom is sufficiently far out.

**Comment by UnHumbleBen** [comment]
https://github.com/UC-Davis-molecular-computing/scadnano/commit/d8d0151018d7df0b53af073553708f4a27ece4da

**Comment by dave-doty** [comment]
Great!

However, it seems to pan and zoom quite sluggishly (on both Chrome and Firefox) even when the "show DNA" checkbox is unchecked.

I haven't dug into the implementation yet, but hopefully this can be implemented in a way that requires no extra processing, compared to before, when "show DNA" is unchecked. Do you notice this too? For instance, when I zoom out, instead of being smooth, it waits a few seconds and then suddenly shows the zoomed out image.

Also, the slowdown persists; it doesn't appear to be associated with the single "create the cached image" event. I would expect there to be a slowdown when the cached image is first created, but after that it should be at least equally as fast to render.

If it's not clear where the slowdown is coming from, try the "Performance" tab of developer tools.

**Comment by dave-doty** [comment]
Oh wait, there's a bug. I filed it: #212
