### ISSUE TITLE
Update mismatches in the view when helices change

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#304]
Similar to #237 but applied to mismatches instead of modifications. Mismatches are drawn correctly when helices are removed, but not when "Display only selected helices" is checked. (They seem to default to the position they would be if all helices are displayed).

**Comment by UnHumbleBen** [comment]
@dave-doty 

https://github.com/UC-Davis-molecular-computing/scadnano/blob/a2b6e5f5e81c2a30b52ceaf0f26efb108165a5ef/lib/src/view/design_main_mismatches.dart#L34-L35

I don't understand what this FIXME is for, is there a reason why you didn't use the `props.dna_design`?

I'm planning to replace that line with:
```
 var helix = props.dna_design.helices[substrand.helix]; 
```

**Comment by dave-doty** [comment]
Hmm, I know I recently added dna_design as a prop to fix that FIXME. But I must have forgotten to actually change the line of code. Yes, please change it to reference props.dna_design (and remove the parameter dna_design from the method).
