### ISSUE TITLE
make width of File menu just enough to fit all entries on one line

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#339]
Currently, the option "Warn on exit if unsaved" wraps on the last word to a new line, which is ugly:

![image](https://user-images.githubusercontent.com/19274365/86500138-f3440080-bd43-11ea-8d0b-d8ef1ca59064.png)

**Comment by UnHumbleBen** [comment]
This was how I fixed it for the view checkbox:
https://github.com/UC-Davis-molecular-computing/scadnano/blob/e60b1e709326a769990a44ab6e91910a1e8f2eeb/web/scadnano-styles.css#L677-L680

Perhaps remove `#view-nav-dropdown` so that it applies to all checkboxes.
