### ISSUE TITLE
add option to not save DNADesign in localStorage on every edit

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#348]
On large designs (e.g., 25,000 strands), this causes a significant slowdown.

Here's the Chrome profiler on creating a nick in such a design:

![image](https://user-images.githubusercontent.com/19274365/86621164-91b5a900-bf72-11ea-9ae7-84d707977e74.png)

Here's the same thing with writing to localStorage disabled:

![image](https://user-images.githubusercontent.com/19274365/86621091-6af77280-bf72-11ea-8a65-cd20397f63e4.png)

As you can see, it adds about a 0.9 second delay.

**Comment by rishabhmudradi** [comment]
Should this feature be added under 'Edit' in the main menu?

**Comment by dave-doty** [comment]
Let's put it under "File".

Note that this will require messing with the local_storage "middleware". Let me know if you want to chat about how that works.

**Comment by rishabhmudradi** [comment]
I think a short conversation might be helpful for me, I'm free anytime after 2 at your convenience.

**Comment by dave-doty** [comment]
Closed in https://github.com/UC-Davis-molecular-computing/scadnano/commit/a8bf5cda5d247635b965d871092e343ae197b74b
