### ISSUE TITLE
add convenience chained methods for making Designs as in Python library

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#387]
In the Python library, one can do chained method calls such as

```python
design.strand(1,8).to(16).cross(2).to(4)
```
to add a two-domain strand on helices 1 and 2.

It would be useful for writing unit tests to have such methods in the Dart library as well.

After writing this, the unit tests should be re-written to use these to create designs.

**Comment by dave-doty** [comment]
In Dart, because the objects are immutable, this won't work exactly as in Python. In Python, each method returns a `StrandBuilder` object.

We could create a new non-immutable class. We can't call it `StrandBuilder` because that's taken by the built_value implementation for `Strand. But we could call it `StrandAdder`, for instance. A `StrandAdder would work like the `StrandBuilder` in Python: it keeps track of the `DNADesign` object that created it in the call to `design.strand`. 

The difference from the user's perspective is that we would need to final call to actually create a new `DNADesign` (since we can't mutate the existing design as in Python). So this would be used like this:

```dart
design = design.strand(1,8).to(16).cross(2).to(4).commit();
```

The call to `.commit()` actually rebuilds the `DNADesign` with the new `Strand`; prior to that, the calls are just building up domain information in the `StrandAdder` object.

This might actually be simpler to write than the Python code. The Python code is complicated by the fact that the design needs to be modified on every call to `to`, just in case that is the last call in the chain.

**Comment by rishabhmudradi** [comment]
Should I create the 'StrandAdder' class inside the test folder?

**Comment by dave-doty** [comment]
No, although this will be useful for testing, it should just be a part of the regular scadnano library. Put it in the state subfolder.
