### ISSUE TITLE
create concrete protocol for interpreting position, svg_position, grid_position in Helix

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#39]
Currently the way that these three fields interact is only partially documented, with some implicit behavior. Devise a concrete way to interpret what to do when one or more of these is absent. Also decide on and implement a concrete scheme for representing "absence" (e.g., setting a field to null, or setting it to its default value if initially null).

**Comment by dave-doty** [comment]
As a first step, implement pitch in the main view as rotation. That should be usable to visualize this origami nicely: http://www.qianlab.caltech.edu/nnano.2016.256-s1.pdf (Figure S71).

**Comment by UnHumbleBen** [comment]
Is the rotation of pitch about the origin (0, 0, 0)? Or is the rotation about some other point?

**Comment by dave-doty** [comment]
Sure, that makes sense.

**Comment by dave-doty** [comment]
One thing that is odd about the current design is that `Helix.rotation` and `Helix.rotation_anchor` are redundant with `Helix.position.roll`. I chose `Helix.rotation` and `Helix.rotation_anchor` because currently the way the rotation is set in the main view is by setting the rotation angle to be straight up or down at a particular offset (which is the anchor). But this could be translated to a global roll angle for the whole helix, and probably is best represented as such.

It's not clear whether `Helix.position.yaw` would ever make sense to show in the main view. Same with `Helix.position.x`. They both go "in and out of the screen". But `Helix.position.pitch` makes total sense. It simply rotates the helix in the plane of the screen. This could be used to implement designs that have not all helices in parallel, for example, 

http://qianlab.caltech.edu/nnano.2016.256.pdf
http://qianlab.caltech.edu/nnano.2016.256-s1.pdf

**Comment by dave-doty** [comment]
Marking this as closed, since this has been worked out. There is still the matter of helix pitch and yaw, which will be removed soon, but this issue wasn't really addressing that.
