### ISSUE TITLE
turn off Redux DevTools automatically when deployed

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#399]
Currently React DevTools is enabled by a const value in lib/src/app.dart.

Instead, it should be controlled from a source that can be set to false when deployed but true when running locally. This way, we won't have to remember to set that constant to false before committing.

**Comment by UnHumbleBen** [comment]
This is general done by using environmental variables. I can try looking into this when I have the time.

**Comment by dave-doty** [comment]
Great!

**Comment by UnHumbleBen** [comment]
@dave-doty Is this the only line that needs to be set to disable the devtools?
https://github.com/UC-Davis-molecular-computing/scadnano/blob/dc1e16f3209f71239fff5a672b2b5101f4426927/lib/src/app.dart#L40

The issue says "React DevTools" but I think you meant Redux. If you also want to disable React Dev Tools, looks like something like this: https://remarkablemark.org/blog/2017/01/25/disable-react-devtools/

**Comment by dave-doty** [comment]
> @dave-doty Is this the only line that needs to be set to disable the devtools?

Yes.

> The issue says "React DevTools" but I think you meant Redux. If you also want to disable React Dev Tools, looks like something like this: https://remarkablemark.org/blog/2017/01/25/disable-react-devtools/

Yes, I meant "Redux".

I think React DevTools does not require doing anything differently in the source code, so probably does not incur a slowdown on the production server.
