### ISSUE TITLE
add axis arrows to main view and side view

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#403]
The conventions for interpreting geometry in the side view and main view are a bit convoluted, and buried somewhere in the README text. It is particularly tricky if "invert y axis" is selected, since the z axis must also be inverted, or the perspective must be switched, so that now we imagine the side view is looking from right to left in the main view (instead of from left to right as it normally is).

It would be easier to follow what's going on if these ideas were explicitly displayed in the side view and main view, using cartesian axis arrows, and possibly some representation somewhere of what the side view represents relative to the main view (i.e., an eye looking in one direction left or right at a depiction of a design).

**Comment by rishabhmudradi** [comment]
Hi Professor, just wanted to confirm that you wanted us to remove the "eye" portion of this feature.

**Comment by dave-doty** [comment]
> Hi Professor, just wanted to confirm that you wanted us to remove the "eye" portion of this feature.

Yes, it's not particularly clear what it means, and I can't think of a way to make it clearer.
