### ISSUE TITLE
add view option to show length of loopout next to loopout

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#426]
Currently, it is shown in the browser on mouseover. However, this would be useful for making figures that don't show the DNA sequence (which implicitly tells the length of the loopout), to be able to read the fully-specified design from the exported SVG figure.

**Comment by dave-doty** [comment]
This should anchor the text to the path, similarly to how DNA sequences for insertions are anchored. That way, no matter how we change how loopouts are drawn in the future (e.g., for #17), it will still look okay.

**Comment by rishabhmudradi** [comment]
Should I enforce the rule that in order to have loopout lengths displayed, show DNA sequence has to be false?

**Comment by dave-doty** [comment]
I think they could both be drawn, if the length is on the opposite side. I think currently the DNA sequence is drawn "above" the curve, so the length can be "under" the curve.

Look at the code for drawing DNA sequences on insertions, and drawing text showing the number of insertions:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/lib/src/view/design_main_strand_insertion.dart
https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/lib/src/view/design_main_dna_sequence.dart

In particular, link the text to the curve, using `textPath` and `text` elements similarly to here:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/5f49e6dccba80ae246273c89cd7697c281a7d938/lib/src/view/design_main_strand_insertion.dart#L122-L149

Note that my most recent commit gets rid of two constants that previous were in those files. Any numbers that move things around should be expressed as multiples of `geometry.base_height_svg` and/or `geometry.base_width_svg`, where `geometry` is the `Geometry` object in the `Design`, e.g.,

https://github.com/UC-Davis-molecular-computing/scadnano/blob/5f49e6dccba80ae246273c89cd7697c281a7d938/lib/src/view/design_main_dna_sequence.dart#L83

https://github.com/UC-Davis-molecular-computing/scadnano/blob/5f49e6dccba80ae246273c89cd7697c281a7d938/lib/src/view/design_main_dna_sequence.dart#L84

Code like this tends to be ugly to calibrate it just right, but that's how it works.

**Comment by rishabhmudradi** [comment]
I was looking through designs with loopouts to account for all cases, and came across the loopouts_all_types.sc. 
![Screen Shot 2020-08-04 at 11 12 43 PM](https://user-images.githubusercontent.com/22282701/89378363-7a202c00-d6a8-11ea-9de9-6b40b198c813.png)

In this case should the loopout length still be displayed under the curve?

**Comment by dave-doty** [comment]
> In this case should the loopout length still be displayed under the curve?

Well, the opposite side from where the DNA is. So it would be "underneath" if you rotate your head until the DNA looks right-side up.
