### ISSUE TITLE
properly display cached PNG of DNA sequences, when some helix group is translated to negative y position

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#436]
Now that helix groups can be translated anywhere, the hack in the DNA sequence caching here is no longer working:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/2e6931ad0461b63c1e8fc2ddca53314954a5fd6c/lib/src/view/design_main_dna_sequences.dart#L54-L55

To see how it fails, load the design [origami_cross_tile_strong_strong.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/5036205/origami_cross_tile_strong_strong.zip). When zoomed out it looks like this:

![image](https://user-images.githubusercontent.com/19274365/89555410-e1cb9980-d7c4-11ea-9493-7685c4c78f00.png)

But it should look like this:

![image](https://user-images.githubusercontent.com/19274365/89555458-ed1ec500-d7c4-11ea-8e1f-1e6fc63b035c.png)

I think the problem is that helix group "north" has y translation -11.26 nm (i.e., about -339 pixels in SVG coordinates, much bigger than the -50 in the caching hack).

**Comment by UnHumbleBen** [comment]
The problem exists before helix groups were introduced when helices have negative y coordinate. For example:

[24_helix_origami_rectangle_shift_y.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/5048602/24_helix_origami_rectangle_shift_y.zip)

I wonder if there is a way to find the smallest (most negative) y coordinate of the helix group.

**Comment by dave-doty** [comment]
> I wonder if there is a way to find the smallest (most negative) y coordinate of the helix group.

Sure, if `group_name` is the name of the group (and if extension_methods.dart is included):

```dart
double min_y = [for (var helix in helices.values) if (helix.name == group_name) helix.svg_position.y].min;
```

**Comment by UnHumbleBen** [comment]
Nevermind! I can just use the dna-sequences-main-view group bounding box :D
