### ISSUE TITLE
implement cadnano import/export in Dart code

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#447]
Currently, the cadnano import/export functionality is the only "true web app" functionality, which is farmed out to a serve that executes the Python code maintained on a separate repository.

But I'd like to implement it directly in Dart, both so it doesn't require that server to be up and running, and also because that code, though implemented in the Python library, is also a third repo that needs to be kept in sync when new functionality is added. For instance, at the time of this issue, helix groups have broken that code, even though they are implemented in both the Python library and Dart code.

There are unit tests in the Python library; let's make sure to imitate them in the Dart unit tests as well. (in their own file)

**Comment by UnHumbleBen** [comment]
Closed in https://github.com/UC-Davis-molecular-computing/scadnano/commit/240c1adb91f6e725b88058360012450e4ee3a565
