### ISSUE TITLE
do not select objects on right-click

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#458]
Currently, if DNA ends are selectable, and one right clicks on a DNA end to bring up the context menu, it becomes selected:

![image](https://user-images.githubusercontent.com/19274365/90960418-35411700-e456-11ea-9c51-1480e9a36cb0.png)

This is incorrect behavior; only left-click should select.

**Comment by dave-doty** [comment]
I approved the PR without actually running the code (assuming that it had been tested for the desired behavior).

I just checked this in the latest dev branch, and it's still appears to be happening:

![image](https://user-images.githubusercontent.com/19274365/91237774-54f36c00-e6f0-11ea-84c9-4602a054c9de.png)

I think this code will be relevant:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/b6c8b208ec8623fdbc3c2c45ffa5ab46130d785d/lib/src/view/design_main_strand_dna_end.dart#L171-L176

**Comment by rishabhmudradi** [comment]
I think I made it so if a user right clicks on a dna-end, then it does not get selected. But if a user were to select a dna-end and then right click on a strand it doesn't automatically unselect it. Should I account for the second case too?

![Screen Shot 2020-08-25 at 4 46 21 PM](https://user-images.githubusercontent.com/22282701/91239095-74d85f00-e6f3-11ea-8f8a-edb46ffc12d8.png) 
![Screen Shot 2020-08-25 at 4 53 24 PM](https://user-images.githubusercontent.com/22282701/91239129-8588d500-e6f3-11ea-81fd-a0311926b119.png)

**Comment by dave-doty** [comment]
> I think I made it so if a user right clicks on a dna-end, then it does not get selected. 

I right-clicked on the end itself, and it was selected. Try it out yourself.

**Comment by rishabhmudradi** [comment]
I'm not sure if I am clicking on right area, the dna ends are the sqaure/triangles on the strands right?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22282701/91240314-8707cc80-e6f6-11ea-97ab-79b260834140.gif)

**Comment by dave-doty** [comment]
That's quite strange. I see the behavior on the current dev site, using both Chrome and Firefox.

Can you try Firefox to see if you get the same behavior?

I wonder if it's a Mac/PC thing, where your Mac is not detecting the same click events.

**Comment by dave-doty** [comment]
By the way, I don't see the pink to select it until the up-click, so it's definitely the mouseup event that is causing it.

**Comment by rishabhmudradi** [comment]
I just tried it on Firefox and you were right, the ends still get clicked. It looks like it worked perfectly for chrome on a mac but not on Firefox. I'll fix this issue right now.

**Comment by dave-doty** [comment]
> I just tested this and it looks like on a Mac with chrome, the mouse pointer down method was never accessed when I right-click. On Firefox for example, event.button is printed for both mouse/pointer up and down when I right-click. On the other hand on chrome, the event.button is only printed for mouse/pointer up.

(copied from a PR so we have a record in the issues)

I wonder if the thing that was supposed to be implemented by the left-click down works properly on a Mac. It would be good to meet and try to flesh this out to make sure that there's not some functionality disabled on Mac that should be there.

**Comment by rishabhmudradi** [comment]
Sure, I'm free for the rest of the day so any time is convenient.
