### ISSUE TITLE
add option to show domain name mismatches

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#471]
Domains can be assigned names, which can be shown in the web interface.

The idea is for complementary domains to bind, with one having a * at the end of the name, e.g.:

![image](https://user-images.githubusercontent.com/19274365/92341092-8c0f3900-f071-11ea-8f6e-ef908c484b0b.png)

It would be very useful to have an option to show domain name mismatches, marking when an error such as this occurs:

![image](https://user-images.githubusercontent.com/19274365/92341148-a9440780-f071-11ea-91ee-c71a951667ce.png)

**Comment by dave-doty** [comment]
It is okay to have a domain be entirely single-stranded. But if any part of another domain overlaps, it is considered a mismatch if any of the following happen:

- the domain names are not complementary (i.e., same string, except that exactly one ends with a *)
- the domains do not have exactly the same start and end offsets on the helix.

**Comment by rishabhmudradi** [comment]
I just got started on this and wanted to test my code on a design, is it possible to send me the output file from the above example?

**Comment by dave-doty** [comment]
It's pretty large.

I put a small example in the python scripting repo dev branch: 

https://github.com/UC-Davis-molecular-computing/scadnano-python-package/blob/dev/examples/names_domains_strands.py
https://github.com/UC-Davis-molecular-computing/scadnano-python-package/blob/dev/examples/output_designs/names_domains_strands.sc

Should look like this when loaded:

![image](https://user-images.githubusercontent.com/19274365/92495056-4d7d9980-f1ab-11ea-918b-0d3d911ab968.png)

There should be mismatches on domains 2 (since the names don't match), 4 (since the domain names are exactly equal, not complementary), 5, 6, and 7 (since the overlap is partial in each case), and no mismatches on domains 1 and 3 (since the domain names match) and 8 and 9 (since there is no overlap).

**Comment by dave-doty** [comment]
I suggest following the same pattern as with these components:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/master/lib/src/view/design_main_mismatches.dart
https://github.com/UC-Davis-molecular-computing/scadnano/blob/master/lib/src/view/design_main_mismatch.dart

In fact, you can simply reuse the bottom component. Rename the top one to be "design_main_dna_mismatches.dart" (and the components in it), so that it's clear what is mismatching.

Then just pick a base offset in the middle of the domain (i.e., average the start and end offsets) to place the mismatch at.
