### ISSUE TITLE
Fix side-view cursor title to use y,z coordinate instead of x,y

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#473]
Set grid to none. When you hover the cursor on the side-view, the cursor title uses (x,y) coordinate. You can tell because the first coordinate is always 0, no matter where the cursor moves. Instead, the cursor title should use (y, z) or (z, y) coordinates

**Comment by dave-doty** [comment]
Note this will have to be changed back with #488.
