### ISSUE TITLE
swap position x z coordinate interpretation

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#488]
Undo what was done to close issue #307.

What I didn't realize when that was implemented is that it switched us from a right-handed coordinate system to a left-handed coordinate system. We want to go back to right-handed to make it simpler to export to 3D tools such as [oxDNA](https://dna.physics.ox.ac.uk/index.php/Main_Page).

Let's ensure backward compatibility here by bumping the minor version number once this is fixed, checking the version on import from a `.sc` file, and swapping the x-z coordinates on prior versions.

Related to Python package issue [144](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/144).

**Comment by UnHumbleBen** [comment]
@dave-doty Is this the correct way to access and write to the position field?
```dart
      if (position_x_z_should_swap && grid_is_none) {
        // prior to version 0.13.0, x and z had the opposite role
        num swap = helix_builder.position_.x;
        helix_builder.position_.x = helix_builder.position_.z;
        helix_builder.position_.z = swap;
      }
```
I'm running into weird issues where the fields are still null after I set them.

**Comment by dave-doty** [comment]
Should be. Make sure the builder is being built and re-stored wherever it needs. (I'm not sure which line of code this is.)

**Comment by UnHumbleBen** [comment]
@dave-doty I investigated some more and it turns out the issue has to do with the `grid_is_none` field in particular to dealing with helix groups. The `grid_is_none` field is a global variable variable, but in designs that use helix groups, there is no global grid. Is there a way to know if a `helix_builder` is using None grid?

**Comment by dave-doty** [comment]
It's probably a mistake to have a global `grid_is_none` variable. The grid should be coming from the helix group(s) (and can be different for different groups). This might be a mistaken holdover from the previous setup where there was only one grid.

**Comment by UnHumbleBen** [comment]
@dave-doty Seems like `grid_is_none` is always used with `!using_groups`, so I was thinking:

```dart
      if (position_x_z_should_swap && grid_is_none && !grid_is_none || helix_builder_is_in_none_grid) {
        // prior to version 0.13.0, x and z had the opposite role
        num swap = helix_builder.position_.x;
        helix_builder.position_.x = helix_builder.position_.z;
        helix_builder.position_.z = swap;
      }
```

Any suggestions on getting the `helix_builder_is_in_none_grid` variable?

**Comment by dave-doty** [comment]
I don't know, I'd have to get back into that code and inspect to see. 

If `Helix` has a `grid` field that's not nullable, then perhaps it is always set to be the appropriate grid from the helix's group, then you could that. I'd check the reducers that modify helices when the grid changes to see.

**Comment by UnHumbleBen** [comment]
I think `helix_builder.grid == Grid.none` should work.

It is not nullable:
https://github.com/UC-Davis-molecular-computing/scadnano/blob/36d27dd00b048fb63105951b4afad5c4a4e491a1/lib/src/state/helix.dart#L67

and the `GridChange` action reducer sets `grid` for all helix builders:
https://github.com/UC-Davis-molecular-computing/scadnano/blob/36d27dd00b048fb63105951b4afad5c4a4e491a1/lib/src/reducers/helices_reducer.dart#L461

Don't think any other actions touch the `Grid`

**Comment by UnHumbleBen** [comment]
@dave-doty Thinking of reusing this test:
https://github.com/UC-Davis-molecular-computing/scadnano/blob/36d27dd00b048fb63105951b4afad5c4a4e491a1/test/other_unit_test.dart#L140-L187

Is the TODO comment relevant anymore? Thinking of removing it.

**Comment by UnHumbleBen** [comment]
Another thing to fix is to change the labels and variables associated with https://github.com/UC-Davis-molecular-computing/scadnano/issues/308 (inverting y axis)
