### ISSUE TITLE
Helix horizontal lines drawn incorrectly for non-zero min-offset

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#498]
Here is a helix with a negative min offset:

![image](https://user-images.githubusercontent.com/31255679/97972846-06aabb00-1d7a-11eb-975b-0d50ce280043.png)

**Comment by dave-doty** [comment]
The fix for this will probably also handle #53.

**Comment by UnHumbleBen** [comment]
> The fix for this will probably also handle #53.

It didn't.

**Comment by UnHumbleBen** [comment]
Closed by https://github.com/UC-Davis-molecular-computing/scadnano/pull/499
