### ISSUE TITLE
Cannot change staple color

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano#512]
Abstract: can't change staple color on  https://scadnano.org/dev/

How to reproduce:

1. Select any origami example on  https://scadnano.org/dev/
2. Right Click on a staple then "set color" then change the color then "OK"
3. The color doesnt change

I am using Chrome 1.0.4044.138

**Comment by dave-doty** [comment]
This is strange. I get this same error on https://scadnano.org/dev/, but I cannot reproduce it locally.

When I do run locally, I see the following warning in Dev Tools, which might be related:

![image](https://user-images.githubusercontent.com/19274365/99419429-f681f800-28b0-11eb-81bb-8652af1b2382.png)

That warning also appears on https://scadnano.org/dev/, and here is the exception that gets thrown when you try to change the color. As you can see, it is occurring within the react-color component that we use.

![image](https://user-images.githubusercontent.com/19274365/99419513-0c8fb880-28b1-11eb-891b-04991c310268.png)

**Comment by UnHumbleBen** [comment]
I have a fix ready. I'm wondering if we should consider this as a `hot fix` and directly commit fix to master, updating the version to something like `0.12.2`. I anticipate that there won't be any issues merging since I only need to edit `strand_color_picker.dart` This way, the color picker of version 0.12 will be fix before we upgrade to 0.13.0

**Comment by dave-doty** [comment]
> I have a fix ready. I'm wondering if we should consider this as a **hot fix** and directly commit fix to master (this is broken not only in `dev` but also `master`), updating the version to something like `0.12.2`. I anticipate that there won't be any issues merging since I only need to edit `strand_color_picker.dart` This way, the color picker of version 0.12 will be fix before we upgrade to 0.13.0

Is the bug appearing in master? I don't think it's there, so if not, let's leave master alone for now.

**Comment by UnHumbleBen** [comment]
I can't use color picker on scadnano.org so I think master has this issue also

**Comment by dave-doty** [comment]
> I can't use color picker on scadnano.org so I think master has this issue also

Ah, you're right.

**Comment by dave-doty** [comment]
But anyway, we're going to merge dev into master soon, so I don't think this is worth rushing.

**Comment by UnHumbleBen** [comment]
Was thinking we might want a functioning color picker in v0.12 since this will be permanently deployed.

**Comment by dave-doty** [comment]
> Was thinking we might want a functioning color picker in v0.12 since this will be permanently deployed.

Ah, I see. Sure, go ahead.
