### ISSUE TITLE
Cleanup menu by using submenus

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#515]
After #510 is merged, we will have a new React component called `DropdownMenuRight` which allows us to add submenus. This was used to add links to other scadnano versions.

We may also want to start doing that with some of the clutter on other menus, for example the four ways to save to localStorage under File might be cleaner to have as a sub-menu, or grouping the various "Show/Hide" options in View under a single "Show/Hide" submenu.

_Originally posted by @dave-doty in https://github.com/UC-Davis-molecular-computing/scadnano/pull/510#discussion_r525249201_

**Comment by dave-doty** [comment]
Closed via duplicate issue #557.
