### ISSUE TITLE
option to show cross-section of all helix rolls at a given offset

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#541]
One way is using a vertical bar that can be dragged across all the helices, similar to cadnano. The side view should then show the arrows indicating all backbone angles for all the helices. Currently we are limited to one (if mousing over a domain in backbone mode) or two (if mousing over a crossover).

**Comment by UnHumbleBen** [comment]
How should the user turn on this feature? Should we put this as a View option like "Show slice bar" (cadnano calls it a slice bar), or something else?

**Comment by dave-doty** [comment]
Sure, slice bar is fine. We might use it for things other than looking at backbone angles in the future. (e.g., the way cadnano uses it to quickly draw many scaffold strands in all helices.)

**Comment by UnHumbleBen** [comment]
# Release notes

## Backbone edit mode removed

Backbone edit mode had two main functionalities:

1. Displaying helices backbone angles. This can now be done by using the [slice bar](#slice-bar)
2. Displaying strand and helices data in the footer. This can now be done by enabling ["Display strand and helix details in footer"](Display strand and helix details in footer) from the view menu.

With this change, users no longer need to "disable" editing by switching from an edit mode to backbone edit mode just to view backbone angles or footer data.


## Slice Bar

The web interface now provides a slicebar, which users can drag and move to display the DNA backbone angle of all helices (in a helix group) at a particular offset.

![slice-bar](https://user-images.githubusercontent.com/31255679/103372372-b6ed2500-4a86-11eb-8a50-6384bbaeb35a.gif)

## Display strand and helix details in footer

The footer (bottom of the screen) displays details about the design based on where the cursor is located. If the cursor is on a helix, the helix index and cursor's base offset location is displayed. If the cursor is on a strand, then the strand details will also be displayed.

![footer-details](https://user-images.githubusercontent.com/31255679/103373019-9aea8300-4a88-11eb-9027-f56c3a724df9.gif)
