### ISSUE TITLE
display strand names

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#576]
Feature request: add an option to display strand names. To handle strand name placement I see a few options, some or all could be implemented: (a) Strand name font should be the same colour as the strand, (b) font size is chosen by user (can help reduce clutter by choosing small enough font to preventing overlapping strand names), (c) options could be given as to where to anchor the strand name, for example: one of 5' end or 3' end or first/second/etc crossover, of strand, is anchored to one of the four corners (NW,SW,NE,SE) or 4 side-centers (N,S,E,W) of the bounding box of the strand name.

**Comment by dave-doty** [comment]
One option is to simply write the strand name where the 5' domain is, in the same place where the 5' domain name would be displayed. You can turn on both at once, but then the strand name and domain name will overlap.

One problem is that with DNA sequences and domain names already displayed, we're running out of places to put stuff in between the helices.

**Comment by dave-doty** [comment]
**Update:** We still have a bit more room, so let's put the strand name on top of the domain name (if both are displayed), i.e., further from the strand than the domain name, the way the domain name is currently further from the strand than the DNA sequence.
