### ISSUE TITLE
minor: place Selectable menu below Edit mode menu

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#577]
I suggest that the "Selectable" menu could live below the "Edit mode:" menu, which would give more precious screen real-estate to the design in the main view.

**Comment by dave-doty** [comment]
This was how it once worked, but there are so many options in each menu (Edit that they do not all display properly on smaller laptop screens.

This will be mitigated once we implement #224.

## Workaround
Uncheck the *Select* Edit mode to hide the *Selectable* menu.

![recording](https://user-images.githubusercontent.com/19274365/110214908-b80e4a00-7e5b-11eb-859e-c15f138a4e8f.gif)
