### ISSUE TITLE
Rope select bug on MacOS

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#586]
With 'rope select' selected in the menu, my understanding is that either of shift+click+drag or command+click+drag should give the intended result. However on MacOS + Firefox, both shift/command result in simultaneous rope creation and translation of the entire canvas (and because both are translating together I can't select anything). This does not happen with 'select', i.e. I see the intended behaviour for 'select'. On Chrome the bug (a) did not happen for the first rope select attempt, (b) did happen on the second and subsequent attempts.

**Comment by dave-doty** [comment]
By "drag", do you mean you are keeping the mouse button depressed while you move the cursor? This is not how it is intended to work. To add a new point to the polygon, press the mouse button down, then up, both at the place you want to add a new point, before moving the cursor.
