### ISSUE TITLE
export to oxView format

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#588]
There is a new file format for oxView, which has more information than oxDNA (such as strand names, colors, base pairs). 

scadnano should be able to export directly to this format, since scadnano has such information that can be embedded in the oxView format.

See also issue https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/139

Format explained here: https://github.com/sulcgroup/oxdna-viewer/blob/master/file-format.md

**Comment by Akodiat** [comment]
Here is the addition I wrote for converting to the .oxview format in the [candano conversion script](https://github.com/lorenzo-rovigatti/tacoxDNA#cadnano-to-oxdna-converter):
https://github.com/lorenzo-rovigatti/tacoxDNA/commit/78ec99507420

If you can get correct positions and connectivity for oxDNA, it should be easy to output to oxView as well

I've also added oxview conversion for rpoly (vhelix) and tiamat.

There is no written standard for the oxview format yet, I'm afraid, but you can easily create and test examples by saving and loading structures in oxview: https://sulcgroup.github.io/oxdna-viewer/. And just let me know if you have any questions!

**Comment by dave-doty** [comment]
Now that this is implemented in the Python package (https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/173), this should be easy by translating the export code to Dart.

See how the oxDNA export currently works (in middleware) for an example of how to do this sort of export in general.

**Comment by dave-doty** [comment]
# Release notes

## Export to oxView format
The scadnano web interface can now export to the [oxView format](https://github.com/sulcgroup/oxdna-viewer/blob/master/file-format.md), which (like oxDNA files) can be read the tool [oxView](https://sulcgroup.github.io/oxdna-viewer/).

It has been possible for a while to export to the oxDNA format, but this is nicer just for visualizing scadnano structures in oxView, because 

1. The oxDNA format has two files, whereas oxView has only one.
2. The oxView format includes some extra data such as which bases are paired, and what color strands are. This information is populated with the relevant scadnano data. Have the strands be the same color in each tool makes it easier to figure out which strand is which.
