### ISSUE TITLE
add "assign domain complement from bound strands" option

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#592]
Sometimes we build a structure by copy-pasting strands, in which case we may often use 
"assign DNA complement from bound strands", as in #518 . I'm requesting the same feature for domain names to save lots of manual editing of domain names.

**Comment by dave-doty** [comment]
This means if domain `a` is bound to `b`, and `a.name="xyz"`, and `b.name` is undefined, then after using this feature, we would have `b.name="xyz*"`?

**Comment by damienwoods** [comment]
yup
