### ISSUE TITLE
assign domain complement from bound domains if domains are selected (instead of whole strand)

### ISSUE THREAD

**Issue by cehsour** [UC-Davis-molecular-computing/scadnano#614]
An addition to issue #592 specifically for computing the complement from bound domains. The same context menu item does this action, but if domains are selectable, then individual selected/clicked domains are assigned names, instead of assigning to all domains on a strand.

**Comment by dave-doty** [comment]
Has this issue been handled by PR #616?

I see that "closes #614" is in the title of that PR, but not any commit message. Be sure to put "closes #614" in a commit message. The GitHub action that automatically generates release notes gathers together all the commit messages, and this helps to identify which issues were closed and might require more explanation/documentation in the release notes.

See some releases for examples of how the commit messages get collected: https://github.com/UC-Davis-molecular-computing/scadnano/releases

If it has been handled, then add the label "closed in dev". The issue will be closed automatically once the changes make their way to the main branch. (So keep the issue open in GitHub.)
