### ISSUE TITLE
move context menu position when it doesn't fit into window

### ISSUE THREAD

**Issue by sarahayu** [UC-Davis-molecular-computing/scadnano#618]
Ideally will be implemented with #557 
By default, the context menu should appear to the bottom-right of the cursor, but if it appears out of bounds of window it should be moved to the left/top of cursor. Submenus should be dealt with similarly

**Comment by dave-doty** [comment]
> if it appears out of bounds of window it should be moved to the left/top of cursor

Or a hybrid. Perhaps a more flexible approach is to calculate where the bottom of the context menu will appear and then translate the menu up by the quantity `min(0, y_coordinate_of_context_menu_bottom - y_coordinate_of_viewport_bottom)`.

**Comment by dave-doty** [comment]
Closed in 62da977
