### ISSUE TITLE
create dropdown menu UI (e.g., File, Edit, Help, etc.)

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#63]
Currently the options selectable by the user at just some checkboxes across the top of the screen, plus some buttons on the right. This is ugly and it isn't scalable.

Create a standard dropdown menu (a.k.a. curtain menu) to be able to set all of these options.

**Comment by UnHumbleBen** [comment]
@dave-doty I started looking into the library. I think we should replace the entire MenuComponent with [Navbar](https://react-bootstrap.github.io/components/navbar/). I think we should plan out what the menu UI should look like (what buttons and options there are).

**Comment by UnHumbleBen** [comment]
Closed by commits from https://github.com/UC-Davis-molecular-computing/scadnano/commit/61cae84b86092ecb2d72a30433c3a86d37c41102 to https://github.com/UC-Davis-molecular-computing/scadnano/commit/8894cc0a66641094703033614ff24ce33e79c7b3
