### ISSUE TITLE
fix Helix.roll translation to nucleotide positions in oxDNA export

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#633]
The oxDNA export does not use Helix.roll values calculate all nucleotide positions correctly. Load the example design perfect.sc contained in this zip file: [perfect.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/6911830/perfect.zip). It should look like this in scadnano: 

Select *View&rarr;Invert y- and x-axes* in scadnano to make the helices appear in the order as below. This makes the view closer to the default view in oxView.

![image](https://user-images.githubusercontent.com/19274365/127752441-ea12be4c-6cd5-455e-91be-babff15cc4fd.png)

The crossover is "perfect": the backbone of each domain is optimally close to the other helix, i.e., the red arrows in the side view are pointed directly at each other.

Click *Export&rarr;oxDNA* to save files perfect.dat and perfect.top. They are contained in the same zip file [perfect.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/6911830/perfect.zip).

Open [oxView](https://sulcgroup.github.io/oxdna-viewer/) and click *Open* on the upper left of the screen. Drag the two files perfect.dat and perfect.top onto the "drop it here" window and click the "Open" button (the one that appeared in this inset window):

![image](https://user-images.githubusercontent.com/19274365/127753149-66cf83ad-4af6-4635-b041-b8936252b941.png)

to load the design in oxView. It should look like this at first, which shows a horizontal mirror image of the scadnano main view:

![image](https://user-images.githubusercontent.com/19274365/127752672-8eed2e65-7989-47e5-90af-567300de9f64.png)

The gold strand in oxView is the same as the red strand in scadnano. The dark blue oxView strand is the same as the green scadnano strand, and the light blue oxView strand is the cyan scadnano strand.

Zoom in, and click the right side of the screen, dragging to the left to rotate by 90 degrees (i.e., rotate until the blue axis arrow pointing left above in oxView above is pointing into the screen). This will show the oxView equivalent of the side view in scadnano:

![image](https://user-images.githubusercontent.com/19274365/127752589-d7f8c568-1149-4641-b613-109131c8ea17.png)

Note that on helix 1 (the top helix in both views), the backbone positions of each strand are almost exactly the same as in scadnano:

![image](https://user-images.githubusercontent.com/19274365/127752609-90a69e6c-1396-423a-b84c-8c9b6c30bc3d.png)![image](https://user-images.githubusercontent.com/19274365/127752605-fb3f9520-b6fb-4dc6-a0be-ffec69aea7e8.png)

I say "almost" because the gold line joining the red base in the center of the helix to the gold backbone at the bottom of the  helix should be exactly parallel to the green axis line in the background (i.e., the gold line should point straight down), though they are very slightly not parallel (the gold line points down and slightly to the left), but this is not the major problem.

The major problem is that, on helix 0 (the bottom helix in both views), the backbone positions are rotated 60 degrees counterclockwise from their scadnano positions:

![image](https://user-images.githubusercontent.com/19274365/127752626-b46fd065-50c6-49e7-b482-05721d6caa5e.png)![image](https://user-images.githubusercontent.com/19274365/127752630-836c1c2a-39fb-4b16-b567-a99e66bceb42.png)

**Comment by dave-doty** [comment]
See also https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/188

**Comment by DanielHader** [comment]
I figured it out! The roll angle was being applied counterclockwise instead of clockwise.
