### ISSUE TITLE
make scadnano pitch angle agree with oxDNA

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#667]
**Note:** This is a breaking change since it will change how oxDNA output works.

Currently, scadnano interprets the pitch angle as a clockwise rotation in the Y-Z plane, following SVG convention. The following design has a helix group (containing helix 1) with pitch=45 (clockwise, away from the single strand on helix 0):

![image](https://user-images.githubusercontent.com/19274365/140661971-de0ef47d-e112-464c-b49c-34003d7b43c9.png)

However, exporting to oxDNA rotates the helix in the opposite direction (counter-clockwise, towards the single strand on helix 0):

![image](https://user-images.githubusercontent.com/19274365/140661970-f1d2367a-7adb-4bd1-aa71-9cc290226dac.png)

The two conventions should match, either by rotating counter-clockwise in the scadnano main view, or by changing the oxDNA export code to rotate clockwise in the Y-Z plane. **UPDATE:** We changed the oxDNA export to rotate clockwise in the Y-Z plane.

**Comment by UnHumbleBen** [comment]
@dave-doty I am working on the release note and have some questions:

Firstly, which option was used to resolve this issue? You discussed two options here but which one was chosen?
> The two conventions should match, either by rotating counter-clockwise in the scadnano main view, or by changing the oxDNA export code to rotate clockwise in the Y-Z plane.

Secondly, I would like to take a screenshot of either scadnano or oxDNA after the fix. Can I have the scadnano or oxDNA file generated after the fix? Or at the very least, the scadnano file so I can generate the oxDNA file myself?

**Comment by dave-doty** [comment]
> The two conventions should match, either by rotating counter-clockwise in the scadnano main view, or by changing the oxDNA export code to rotate clockwise in the Y-Z plane.

We chose the second, altering the oxDNA export to rotate clockwise in the Y-Z plane.

> Secondly, I would like to take a screenshot of either scadnano or oxDNA after the fix. Can I have the scadnano or oxDNA file generated after the fix? Or at the very least, the scadnano file so I can generate the oxDNA file myself?

I don't think I saved it. :) But it was fairly straightforward to make.

**Comment by UnHumbleBen** [comment]
> I don't think I saved it. :) But it was fairly straightforward to make.

I see, I had difficulty figuring out precisely what combination of grid position for helix 1 / helix group position for the rotated helix group you used for the design. Do you remember what values you choose? I could probably figure it out from playing around but just in case you happen to remember

**Comment by dave-doty** [comment]
I set the angle of the second HelixGroup to 45, and then in Move Helix edit mode, I dragged the group until it appeared where it is.
