### ISSUE TITLE
adjusting helices view order should update view

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#677]
Click on Group&rarr;adjust current group, and change the helices view order. It does not update the view. It does save the change in the design so that if you refresh the page, the new view order is displayed.

**Comment by dave-doty** [comment]
Figured out the problem. The reducer `helix_group_name_change_reducer` is poorly titled because it assumes that the only thing it has to worry about changing in the group is the name. Not true. If `helices_view_order` changed, then Helix SVG positions need to be recalculated.

Let's make this a global reducer so we can check the old value of `helices_view_order` in the old state. If it equals `helices_view_order` in the new group, don't re-calculate SVG positions, otherwise do. (See examples in other reducers in this file for how to recalculate.) Also remove `name_` from the reducer's function's name.

**Comment by UnHumbleBen** [comment]
I'll take care of this issue, unless someone else already started on it

**Comment by sarahayu** [comment]
feel free, I don't think the rest of us have touched on it yet
