### ISSUE TITLE
import/export cadnano files

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#7]
Add ability to read from and write to files in the [cadnano](https://cadnano.org/) JSON format.

Now that we have a proper menu, these should go under the File menu as "Import cadnano v2" and "Export cadnano v2".

**Comment by UnHumbleBen** [comment]
Closed by https://github.com/UC-Davis-molecular-computing/scadnano/commit/2745eaee31ae2f8657706bfe0e82eea96a3f6593
