### ISSUE TITLE
moving domain should be disallowed if overlapping another domain

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#722]
There seems to be a bug that allows me to make an illegal configuration, with overlapping strands. Example: 

Selected some domains, for dragging:
![Screenshot 2022-01-13 at 20 45 36](https://user-images.githubusercontent.com/40836180/149406752-c1a34ab2-c6b3-4716-ac01-c97c3b4f4547.jpg)

After dragging two strands are overlapping: 
![Screenshot 2022-01-13 at 20 46 08](https://user-images.githubusercontent.com/40836180/149407065-3beba0ac-6b8b-473a-9873-78270a5d9445.jpg)

Strands should have turned grey and system disallowed me from dragging to this position.

**Comment by dave-doty** [comment]
There's a check for this, but there's some bug. Here's a minimal reproducible example (if there's only two domains in the design then the check succeeds and the domains cannot be moved to overlap):

![image](https://user-images.githubusercontent.com/19274365/149506740-2c6000a2-daee-44a6-9ff1-71d612e45616.png)

Moving the first domain over the second succeeds but should not:

![image](https://user-images.githubusercontent.com/19274365/149506919-450f0e27-109c-440a-86ba-a5412d1db1ed.png)


![image](https://user-images.githubusercontent.com/19274365/149506815-7699e1d4-8c22-48b6-adb6-5f3dda81d5c8.png)

However, if the third domain is not present, then the move is prevented as it should be:

![image](https://user-images.githubusercontent.com/19274365/149507025-b93bf9dd-219e-4eea-9979-f8c1cb63e4e3.png)
