### ISSUE TITLE
change length of modification "connector"

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#743]
See also https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/212.

By default a "connector" is shown between a strand and a modification, which resembles a hydrocarbon chain:

![image](https://user-images.githubusercontent.com/19274365/151579709-e3dd0d6d-74d1-4bcc-a2c1-f58c79e5b88e.png)

One can turn off the connector for all modifications in the View menu.

![image](https://user-images.githubusercontent.com/19274365/151579777-2934bc9b-1941-445c-a4ac-31547edb95cc.png)

![image](https://user-images.githubusercontent.com/19274365/151579805-2e4c7ead-ed7f-4b98-858f-7b32c44cde92.png)

However, when modifications are close to each other (e.g., FRET pairs or fluorophore-quencher pairs), then they can overlap: 

![image](https://user-images.githubusercontent.com/19274365/151580127-04367969-3b74-4cb3-afdb-a44140482286.png)

So it would be helpful to be able to set a connector length on a specific modification, so that it is displayed at a different vertical height than others.

**Comment by damienwoods** [comment]
Thanks!

**Comment by dave-doty** [comment]
# Release notes

You can now change the length of the modification "connector". By default it is drawn like a carbon chain with 4 links:

![image](https://user-images.githubusercontent.com/19274365/151944535-37739dbc-7a61-4d59-90b3-7e713bf0a325.png)

By editing the modification's connector length:

![image](https://user-images.githubusercontent.com/19274365/151944581-5a8d5988-bd2a-406d-b4d1-8434f40cd887.png)


You can change the length. This is especially helpful to display modifications close to each other on a helix without their text overlapping:

![image](https://user-images.githubusercontent.com/19274365/151944658-93bf0187-a583-4ea6-a380-e9cbb734855d.png)
