### ISSUE TITLE
disable display of helices in main view

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#746]
Scadnano screenshots can look very cluttered in presentations, or in a figure for a paper, where one wants to focus on the 2D strand arrangment and nothing else. For screenshots in presentations, or just showing less clutter in general, it would be good to have the ability to toggle on and off the displaying of helices in the main view.

**Comment by dave-doty** [comment]
Or even better to implement #740.

But this is much easier to implement and can be done fairly quickly.

**Comment by dave-doty** [comment]
# Release notes

## Disable display of helices in main view

Go to View&rarr;Helices&rarr;Show main view helices:

![image](https://user-images.githubusercontent.com/19274365/152549923-f1eb3d43-69c7-432a-972b-cbe388621596.png)

Toggling it will turn off all view elements associated with helices, such as tick marks, helix circles with indices, major tick numbers, etc:

Before:

![image](https://user-images.githubusercontent.com/19274365/152550136-960ebba3-8fee-44d4-b579-08c9f175d226.png)

After:

![image](https://user-images.githubusercontent.com/19274365/152550185-afddfdc7-3f10-4263-af1e-6975af04a036.png)
