### ISSUE TITLE
Github action for dart format

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#778]
Once #777 is implemented, add a GitHub action that automatically sees if dart format would change any file in lib/ and generates an error if so.

See 

https://github.com/DNA-and-Natural-Algorithms-Group/alhambra/blob/80fe16fdc86836e1cab952882772711f296b5671/.github/workflows/python-package.yml#L24-L36

for an example of how this is done for Python. (Not sure how to do the same for Dart.)

**Comment by abhishekgokhale** [comment]
This issue can be closed since this was implemented as part of #777
