### ISSUE TITLE
Export colors to CSV file

### ISSUE THREAD

**Issue by mmguar** [UC-Davis-molecular-computing/scadnano#787]
A useful feature of cadnano is the ability to export strands with their color saved in a column, which lets one group strands very easily for any sort of post-processing. I might have missed it, but I could not find a way to do it when exporting a scadnano csv.

**Comment by dave-doty** [comment]
It wouldn't be hard to add just this feature. There's all kinds of other information about strands also not exported to the CSV file, and I'd be hesitant to clutter up the interface with all of them and have to remember to keep it updated.

If you are writing a program to parse the CSV file, I'd recommend instead using the [scadnano Python package](https://github.com/UC-Davis-molecular-computing/scadnano-python-package#readme) for dealing with the design programmatically. Then you can read in the design and manipulate the strands using all the information available about it, including the color:

```python
import scadnano as sc
design = sc.Design.from_scadnano_file('my_design.sc')
sorted_strands = sorted(design.strands, key=lambda strand: strand.color.hex_string)
```

But, I can imagine you aren't doing any programming, just loading the CSV file into a spreadsheet program like Excel, and you want to be able to use Excel to sort the strands by color for you. If that's the case I could see about an elegant way to implement this feature.

If you are using the color is a proxy for some sort of extra information about a "group" the strand is in (e.g., strands with 5' fluorophores are one color and those with 3' quenchers are another color), then the field `Strand.label` is useful for doing this more cleanly. A label is any (serializable) Python object, such as a string, storing an arbitrary piece of information about a strand. Unfortunately there's no way currently to edit the label in the web interface (see #469), so it's really only an option for writing scadnano scripts, but I can probably figure out some way to implement that in the web interface as well if it would help. In the meantime you can do the hack I do and put that information in the strand name in a way that's easy to parse.

**Comment by mmguar** [comment]
No, that is a great idea. I was using scadnano as I would use cadnano, but the python import is exacty what I need, as that's where all the post-processing happens.
I just did not realize it was possible. I personally don't need this feature then, but it might be useful to someone else.
Thanks!
