### ISSUE TITLE
fix bug with moving potential crossover from one DNA end to another

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#810]
The behavior implemented in this PR is not working anymore:

https://github.com/UC-Davis-molecular-computing/scadnano/pull/729

It was for issue #716.

**Comment by dave-doty** [comment]
Here's a design where it fails (in pencil mode, try moving the crossover from the 5' end of the red domain on helix 0 to the 5' end of the darker green domain on helix 0 as shown below:

![image](https://user-images.githubusercontent.com/19274365/202818819-d2f09d22-128e-4a38-9f64-52a768f28ae9.png)

[2_staple_2_helix_origami_deletions_insertions_mods.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/10045438/2_staple_2_helix_origami_deletions_insertions_mods.zip)

**Comment by sarahayu** [comment]
The issue arises because the darker green domain doesn't have a DNA sequence attached to it. Should we show a warning to the user and forbid creating a crossover between domains that do and don't have DNA sequences, or should we allow the crossover (and don't show a warning) and put wildcards on the non-DNA domain?

**Comment by dave-doty** [comment]
> The issue arises because the darker green domain doesn't have a DNA sequence attached to it. Should we show a warning to the user and forbid creating a crossover between domains that do and don't have DNA sequences, or should we allow the crossover (and don't show a warning) and put wildcards on the non-DNA domain?

The latter. Create wildcards for domains with no DNA assigned.
