### ISSUE TITLE
fix oxDNA export bug with incorrect helix coordinates in 3D

### ISSUE THREAD

**Issue by zoombya** [UC-Davis-molecular-computing/scadnano#811]
Hi guys, great thanks for your work.
I have a great problem with exporting structures from scadnano to oxDNA.
1) any 3D structure designed in scadnano if I directly export to oxDNA get's flattened *regardless* of the lattice.
2) if I first export the structure to candnano2 and import using taco -> the structures look turned inside out.
Attached is a 12hb  exhibiting all these issues.
And screenshots of the 2 mentioned export options.
[220921_0845_12hb_1kb.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/9628772/220921_0845_12hb_1kb.zip)
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1756978/191831939-6079e9cc-5516-432d-bb61-30c538fe2079.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1756978/191831972-80fa44f6-abd4-40f5-8872-e10ffda80187.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1756978/191832228-4089da7f-88fe-4041-901f-890b98f627cc.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1756978/191832280-5ffef685-bb09-4a8d-83c0-fb5dc5819c21.png">

**Comment by dave-doty** [comment]
Hmm, I can reproduce this behavior. Not sure what's going on.

I tried exporting with the Python package and it seems to work: 
![image](https://user-images.githubusercontent.com/19274365/191834554-fdf68c5c-c779-4c68-a004-bdacb4e40618.png)

So I suggest that as a workaround for you for now. Install the scadnano Python package using the instructions here: https://github.com/UC-Davis-molecular-computing/scadnano-python-package#installation

Then put this code in a file named `export.py`:

```python
import scadnano as sc


def main() -> None:
    design = sc.Design.from_scadnano_file('220921_0845_12hb_1kb.sc')
    design.write_oxdna_files()


if __name__ == '__main__':
    main()
```

FInally, run `python export.py` at the command line.

It will generate two files `export.dat` and `export.top`.

**Comment by zoombya** [comment]
great thanks, Dave.
It happens in both Hex and SQ lattices.

**Comment by dave-doty** [comment]
Here's a minimal example of the problem. It appears 3D coordinates are simply being calculated incorrectly, possibly by the function `util.grid_position_to_position3d`. This also fails to convert the square grid to the none grid:

In square grid:

![image](https://user-images.githubusercontent.com/19274365/192157482-02ddef88-225c-4c43-95a4-f636dae2903d.png)

After converting to none grid:

![image](https://user-images.githubusercontent.com/19274365/192157492-a9343797-37fa-477e-ac24-0e9837e91c97.png)

In the above image, helices 1 and 2 are on top of each other.
