### ISSUE TITLE
ensure DialogType is specified each time constructor is called

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#815]
I found a bug when right-clicking on a domain and clicking "set domain name". It was due to the parameter `type` not being specified when calling the `Dialog` constructor. (https://github.com/UC-Davis-molecular-computing/scadnano/pull/816/files)

This may be the only instance, but we should check all calls to the `Dialog` constructor to ensure that `type` is specified.

**Comment by homaho1** [comment]
I've looked over them. All 28 calls to the `Dialog` constructor now contain `type`.

**Comment by dave-doty** [comment]
Super, thanks. Closing the issue.
