### ISSUE TITLE
change color of warning star for domain name mismatch

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#819]
It is too easy to confuse it with a DNA base mismatch; see issue #818.

This should be done by adding a prop `color` to `DesignMainWarningStar`, which is red for a DNA base mismatch but some other color for domain name mismatches. Perhaps blue or green, but it should be something that stands out in a large design and is easy to notice.

**Comment by homaho1** [comment]
Original 
<img width="1191" alt="Screen Shot 2022-10-04 at 5 28 15 PM" src="https://user-images.githubusercontent.com/78931864/193954466-1875fefb-178e-4ff4-84e4-67c4f9932d4d.png">
New
<img width="1354" alt="Screen Shot 2022-10-04 at 5 28 07 PM" src="https://user-images.githubusercontent.com/78931864/193954367-2a5acfb7-86bc-438f-9cf1-3630de46abd0.png">
Is this how you want it to look for domain name mismatch?

**Comment by dave-doty** [comment]
Looks good.
