### ISSUE TITLE
fix github pages deployment

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#824]
I merged dev into main via #823. This triggered the action that deploys to the site scadnano.org, which is (I believe)

https://github.com/UC-Davis-molecular-computing/scadnano/actions/runs/3281808663

The action appeared to run without error.

The newest stable version of scadnano is 0.17.8: https://github.com/UC-Davis-molecular-computing/scadnano/releases/tag/v0.17.8

However, many hours later, and after hard-refreshing on several browsers, scadnano.org still has the old version 0.17.7: 

![image](https://user-images.githubusercontent.com/19274365/196774091-008a2606-eb3d-489f-97b8-3f8cc4ed2846.png)

Determine if there is a problem with the automated deployment and fix.

**Comment by dave-doty** [comment]
Ben Lee (bnllee@ucdavis.edu) set up this automated deployment action. If you have trouble diagnosing the problem, he may have some ideas for how to help.

**Comment by EdwinChang24** [comment]
Not sure if this is the issue, but we are using Ubuntu 18 in the GitHub Actions, which is deprecated and will be unsupported by April next year. We should switch to `ubuntu-latest`.
