### ISSUE TITLE
p7650 vs p7560

### ISSUE THREAD

**Issue by Sam-Davidson** [UC-Davis-molecular-computing/scadnano#863]
![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/43768991/e61b554f-67ed-41f0-bfd6-d03c8dbcdbae)
It looks to me like there is a typo in the web interface when trying to assign an M13 variant, swapping a 5 and a 6. Is there a such thing as p7650? Or was that option supposed to be p7560?

**Comment by dave-doty** [comment]
Looks like a typo, I've corrected it in the dev branch.

**Comment by googee3** [comment]
Great, thanks!
