### ISSUE TITLE
make separate GitHub action for formatting check

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#872]
Right now the formatting check is done in the GitHub action that runs unit tests. Pull that check out into its own separate GitHub action instead, so that it is possible to tell when an action fails whether it was unit tests or formatting, without having to inspect the details of the action.

**Comment by abhishekgokhale** [comment]
Created separate GitHub workflow to check formatting.
However, doing this will slow down checks a bit since all setups will be done twice, once for the formatting and once for the unit tests.

**Comment by abhishekgokhale** [comment]
> Created separate GitHub workflow to check formatting. However, doing this will slow down checks a bit since all setups will be done twice, once for the formatting and once for the unit tests.

I take that back, both workflows ran simultaneously
