### ISSUE TITLE
save SVG file with image of selected objects

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#887]
This is related to #740. That feature seems very difficult to implement due to browser security restrictions about what types of data can be put on the system clipboard.

This issue is a workaround that is slightly more work to use, but avoids the need to work with the system clipboard. Here, we want to save an SVG file. This is similar to what happens when selecting `Export-->SVG main view`, but the difference is that this will make an SVG file out of only the selected objects (the same as what is currently implemented in PR #769), not the entire main view.

This should be straightforward to implement by combining the logic of collecting the selected object SVG, along with the existing logic from saving SVG files.

This should be a new menu item `Export-->SVG of selected objects`.

**Comment by abhishekgokhale** [comment]
Code to close this issue has been pushed, however, I have based the branch from the branch for #740 since there was similar code for both of them. I will make the PR for this branch once this #769 PR is approved and merged, so then the basing would technically be from dev.

**Comment by dave-doty** [comment]
Go ahead and merge #769 if it looks good.

**Comment by abhishekgokhale** [comment]
Need approval to merge #769. Can you approve it so that I can go ahead and create this PR as well?
Thanks!

**Comment by dave-doty** [comment]
Done

**Comment by dave-doty** [comment]
# Release notes

## Export SVG file of selected strands
Previously it was only possible to export the entire main view (view of all strands and helices). Now, you can select some strands and export only them:

![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/19274365/9b72e80c-2a39-4c7e-a3ca-074df190fa04)

Which saves this SVG file:

![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/19274365/6f8eab0b-bafa-41dd-bad6-c10dfaefcfcb)

There is a separate feature (https://github.com/UC-Davis-molecular-computing/scadnano/issues/740) in which selected strands can be copied into an image in the system clipboard and pasted into other programs, such as Powerpoint or Inkscape. However, this is not a SVG image, it is a PNG (bitmap) image that will be pixelated on zoom-in.

This feature takes more work for such transferring of images (since you have to save a file, then import that file into the other program), but retains the vector graphics that remain sharp when zoomed in.
