### ISSUE TITLE
option to display paired bases with gray rectangle

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#897]
Currently "base pair lines" can be displayed, which helps when making figures:

![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/19274365/71d8777e-1223-4dc3-840e-adeddc33dd6a)

Another common convention is to depicted double-stranded regions with a gray rectangle connecting the two DNA strands (e.g., from https://www.solo-group.link/papers/dsd-leakless.pdf, Leakless DNA strand displacement systems, Chris Thachuk, Erik Winfree, David Soloveichik, [DNA Computing and Molecular Programming 21 (DNA21), 2015]):

![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/19274365/cb059658-75f7-4f79-ad15-fdd755a55f8b)

Give this as another view option under View-->Base pairs-->then have a radio button selector (DialogRadio) with three options:

- None
- Lines
- Rectangle

With "... even if bases mismatch" disabled if None is selected.

**Comment by RayBipse** [comment]
Before I implement it, I wanted to double check that I have the correct idea in mind. So we just replace the baselines with a grey rectangle?
<img width="358" alt="Screenshot 2023-12-18 at 12 22 18 PM" src="https://github.com/UC-Davis-molecular-computing/scadnano/assets/46636772/0039586b-b0ef-4a11-b5a3-02b252082ca6">

**Comment by dave-doty** [comment]
> Before I implement it, I wanted to double check that I have the correct idea in mind. So we just replace the baselines with a grey rectangle? <img alt="Screenshot 2023-12-18 at 12 22 18 PM" width="358" src="https://private-user-images.githubusercontent.com/46636772/291399741-0039586b-b0ef-4a11-b5a3-02b252082ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTE3NjMsIm5iZiI6MTcwMzExMTQ2MywicGF0aCI6Ii80NjYzNjc3Mi8yOTEzOTk3NDEtMDAzOTU4NmItYjBlZi00YTExLWI1YTMtMDJiMjUyMDgyY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIyMzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYjk1ZDVhOGQ4ZTkyZTNlODUxYjcxMzgxNzQxZDc2YzllY2Y0NWY0YWZjOWZjMzI4NGMyM2VhZmU4ZjE3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMCtaEts8FWt86JSUOx3GhHDxItmZ1bsUUg5iBBA03o">

Exactly, that looks perfect.
