### ISSUE TITLE
display DNA sequence on extension in order 5' to 3'

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#959]
DNA sequence 5'-TTT ATA ... ATC-3' was assigned to an extension (in scadnano-python by concatenating  `scadnano.Extension(num_bases=len(seq), dna_sequence=seq, display_angle=40, display_length=6)` to a list of strand domains) is being displayed in the wrong (i.e. reverse) order on the bottom of a design. Extensions on the top of a design look fine. 

<img width="528" alt="image" src="https://github.com/UC-Davis-molecular-computing/scadnano/assets/40836180/628f9c74-aa07-4d31-816f-f99294e623e3">

When DNA sequences are exported from the design, this particular DNA sequence is in the correct order.

**Comment by dave-doty** [comment]
Just to illustrate the problem, here are other contexts in which the sequence is backward, the extensions circled in green below:

![image](https://github.com/UC-Davis-molecular-computing/scadnano/assets/19274365/62ebe772-b92b-4000-a201-3ba4296d51e9)

In each case, the strand has sequence 5'-AAATA-CCCCCCCC-AAATA-3'.

So the general problem is that the DNA sequence is always drawn with 5' on left and 3' on right, and the mistake above correspond to cases where the extension reverses that: its 3' end is on the left and its 5' end is on the right.
